# This file was generated by GoReleaser. DO NOT EDIT.
cask "cynative" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "aa2b034f5969788fe478b3cf2a0792b3d7c3192fc757c60177c042be8c29aa52"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f17efc89efb7a141dcda4daca6892784795b77c0f1f904fe77d54da5e67a513d"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "84c2c68556215ab9d1d2ae3133eecaccbeee6c24bf3cf5d6025a5d3a07019576"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c35f60621da2f6e4180fc7f52c2e9b7c7544c769b3cfb54e1a00c806aa15c828"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Linux_arm64.tar.gz"
    end
  end

  name "cynative"
  desc "Agentic security research across your code, cloud and runtime — read-only by construction"
  homepage "https://github.com/cynative/cynative"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cynative"

  # No zap stanza required

  caveats <<~EOS
    Set your LLM provider, model and an API key before first run, e.g.:
      export CYNATIVE_LLM_PROVIDER=anthropic
      export CYNATIVE_LLM_MODEL=claude-opus-4-8
      export ANTHROPIC_API_KEY=...
  EOS
end
