# This file was generated by GoReleaser. DO NOT EDIT.
cask "cynative" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "89000e8f31f5bc47a5c16388ce949f67af6807ed86d0151bdc2e173e345f4a5f"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9ec561a74a354c730850d4e455f205888e204c272c841be30c9af4144b2e1222"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db29a79ddfdc652218ac212f18ed3740399bb099eacd18502b8a264a12b48831"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "22fb47a0c3ce11a10b60f8c4587a9576f85789d8be0485d57b1885dab6f534e6"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Linux_arm64.tar.gz"
    end
  end

  name "cynative"
  desc "Agentic security research across your code, cloud and runtime — read-only by construction"
  homepage "https://github.com/cynative/cynative"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cynative"

  # No zap stanza required

  caveats <<~EOS
    Set your LLM provider, model and an API key before first run, e.g.:
      export CYNATIVE_LLM_PROVIDER=anthropic
      export CYNATIVE_LLM_MODEL=claude-opus-4-8
      export ANTHROPIC_API_KEY=...
  EOS
end
