# This file was generated by GoReleaser. DO NOT EDIT.
cask "cynative" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "ed04aab3e64b92d02aeb6f26c295f297718300ff77baf1e9a1f8f86ecc5ba025"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "17678c3739e96b10f4d30b0f4a011461d8879fbe10624305ba5b298888d31be1"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "959e5a5e79ffd341f1ba0d6693ef9d2391b69b9000c1f82ce6a9246917b96509"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "de8fde52d69c03ab09225013c91624ec4ddecac17a09b93e747329728bf2ffe6"
      url "https://github.com/cynative/cynative/releases/download/v#{version}/cynative_Linux_arm64.tar.gz"
    end
  end

  name "cynative"
  desc "Agentic security research across your code, cloud and runtime — read-only by construction"
  homepage "https://github.com/cynative/cynative"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cynative"

  # No zap stanza required

  caveats <<~EOS
    Set your LLM provider, model and an API key before first run, e.g.:
      export CYNATIVE_LLM_PROVIDER=anthropic
      export CYNATIVE_LLM_MODEL=claude-opus-4-8
      export ANTHROPIC_API_KEY=...
  EOS
end
